server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:com/jxd/report/dao/mapping/*.xml
  type-aliases-package: com.jxd.emp.model
  ##allowPublicKeyRetrieval=true&这个参数来允许公钥检索